# Generated by Django 4.0.3 on 2022-06-10 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electrodomestico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('referencia', models.CharField(max_length=25)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock_elemento', models.IntegerField(default=0, verbose_name='Stock')),
                ('favorito', models.BooleanField(default=False)),
                ('porcentaje_ganancia', models.CharField(choices=[('0.1', '10%'), ('0.15', '15%'), ('0.2', '20%'), ('0.3', '30%')], max_length=10, verbose_name='Porcentaje')),
                ('foto', models.ImageField(blank=True, default='carrito/casa.png', null=True, upload_to='carrito')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Anulado', 'Anulado')], default='Activo', max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Accesorios', 'Accesorios'), ('Productos', 'Productos')], default='Accesorios', max_length=20, verbose_name='Categoría')),
                ('subcategoria', models.CharField(max_length=20, unique=True, verbose_name='Subcategoría')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, help_text='MM/DD/AAAA', verbose_name='Fecha de Registro')),
                ('stock_agregada', models.IntegerField(default=0, verbose_name='Stock Nuevo')),
                ('stock_stock', models.IntegerField(verbose_name='Stock')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Anulado', 'Anulado')], default='Activo', max_length=10, verbose_name='Estado')),
                ('elemento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.elemento', verbose_name='elemento')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(max_length=500, verbose_name='Diagnostico')),
                ('tiposervicio', models.CharField(choices=[('Reparación', 'Reparación'), ('Mantenimiento', 'Mantenimiento')], max_length=20, verbose_name='Tipo de Servicio')),
                ('cantidad', models.IntegerField()),
                ('fallas_basicas', models.CharField(max_length=255, verbose_name='Falla Basica')),
                ('fecha_entrega', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Entrega')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20, verbose_name='Estado')),
                ('electrodomestico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.electrodomestico', verbose_name='Electrodomestico')),
            ],
        ),
        migrations.AddField(
            model_name='elemento',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.marca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='tipo_elemento',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.SET_NULL, to='administrador.tipos_elemento', verbose_name='Subcategoría'),
        ),
        migrations.AddField(
            model_name='electrodomestico',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.marca', verbose_name='Marca'),
        ),
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, help_text='MM/DD/AAAA', verbose_name='Fecha de Registro')),
                ('cantidad_agregada', models.IntegerField(default=0)),
                ('cantidad_stock', models.IntegerField(verbose_name='Cantidad')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Anulado', 'Anulado')], default='Activo', max_length=10, verbose_name='Estado')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.elemento', verbose_name='Producto')),
            ],
        ),
    ]
