# Generated by Django 4.0.4 on 2022-09-10 00:33

import administrador.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_rol_rnombre_alter_usuario_rol'),
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copiaseguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='Copia de Seguridad', max_length=200)),
                ('archivo', models.FileField(upload_to='copiaseguridad', validators=[administrador.models.validate_file_extension])),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorito', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='elemento',
            name='porcentaje_ganancia',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fecha_entrega',
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_entrada',
            field=models.DateField(auto_now=True, help_text='MM/DD/AAAA', verbose_name='Fecha de Entrada'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='observacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Observacion'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='electrodomestico',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='electrodomestico',
            name='referencia',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='diagnostico',
            field=models.CharField(max_length=250, verbose_name='Diagnostico'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='electrodomestico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.electrodomestico', verbose_name='Articulo'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fallas_basicas',
            field=models.CharField(max_length=255, verbose_name='Falla que Presenta'),
        ),
    ]
