"""
Django settings for gestion project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from re import T

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k5%1h-fsycdzyps13o&$d3k2+t84$upa@e#0)fc$*b6wpyba6-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definitionA

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'administrador',
    'usuarios',
    'facturas',
    'crispy_forms',         # pip install django-crispy-forms
    'crispy_bootstrap5',    # pip install django-bootstrap5
                            # pip install crispy_bootstrap5
                            # pip install pymysql
                            # pip install mysqlclient
                            # pip install pillow
                            # pip install django-phonenumber-field[phonenumbers]
]

# Package                  Version
# ------------------------ -----------
# arabic-reshaper          2.1.3
# asgiref                  3.5.2
# asn1crypto               1.5.1
# certifi                  2022.6.15
# cffi                     1.15.1
# charset-normalizer       2.1.0
# click                    8.1.3
# colorama                 0.4.5
# crispy-bootstrap5        0.6
# cryptography             37.0.4
# cssselect2               0.6.0
# Django                   4.0.4
# django-crispy-forms      1.14.0
# django-phonenumber-field 6.1.0
# django-userforeignkey    0.4.0
# djangorestframework      3.13.1
# future                   0.18.2
# html5lib                 1.1
# idna                     3.3
# lxml                     4.9.1
# mysqlclient              2.1.0
# oscrypto                 1.3.0
# phonenumbers             8.12.49
# Pillow                   9.1.1
# pip                      22.1
# pycparser                2.21
# pyHanko                  0.13.2
# pyhanko-certvalidator    0.19.5
# PyMySQL                  1.0.2
# PyPDF3                   1.0.6
# python-bidi              0.4.2
# pytz                     2022.1
# pytz-deprecation-shim    0.1.0.post0
# PyYAML                   6.0
# qrcode                   7.3.1
# reportlab                3.6.11
# urllib3                  1.26.11
# webencodings             0.5.1
# xhtml2pdf                0.2.8

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['gestion/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processor.total_carrito',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_licuadoraspulido',
        'USER': 'root',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Bogota'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'gestion\static'
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# gestion de logueo
LOGOUT_REDIRECT_URL = 'inicio'
LOGIN_REDIRECT_URL = 'inicioadmin'
LOGIN_URL="usuario-login"
 
# para lo del email documentacion django "Alejo3012154053"
EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST="smtp.gmail.com"
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER="facceres1@misena.edu.co"
EMAIL_HOST_PASSWORD="ebsmydwxjufrozjt"

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')