# Generated by Django 4.0.4 on 2022-09-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('Rid', models.AutoField(primary_key=True, serialize=False)),
                ('Rnombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuarios_rol',
            },
        ),
        migrations.CreateModel(
            name='Uadministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Proveedor', 'Proveedor'), ('Trabajador', 'Trabajador'), ('Cliente', 'Cliente')], max_length=13, verbose_name='rol')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('documento', models.CharField(max_length=10, unique=True)),
                ('celular', models.CharField(max_length=10, unique=True)),
                ('tipo_documento', models.CharField(choices=[('C.C', 'C.C'), ('T.I', 'T.I'), ('C.E', 'C.E')], max_length=3, verbose_name='Tipo documento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Uid', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=10, unique=True)),
                ('tipo_documento', models.CharField(choices=[('C.C', 'C.C'), ('T.I', 'T.I'), ('C.E', 'C.E')], max_length=3, verbose_name='Tipo documento')),
                ('rol', models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Proveedor', 'Proveedor'), ('Trabajador', 'Trabajador'), ('Cliente', 'Cliente')], max_length=13, verbose_name='rol')),
                ('Unombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('celular', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(max_length=25)),
                ('ciudad', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Anulado', 'Anulado')], default='Activo', max_length=10, verbose_name='Estado')),
            ],
            options={
                'db_table': 'usuarios_usuario',
            },
        ),
    ]
