# Generated by Django 4.0.4 on 2022-09-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='Rnombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Proveedor', 'Proveedor'), ('Trabajador', 'Trabajador'), ('Cliente', 'Cliente')], max_length=13, verbose_name='rol'),
        ),
    ]
